added optional init params for neal and FSA. included a statemachine …
dainiuskreivenas/rbs pull request #6
Opened 2019-07-19 10:34 UTC by ChrisHuyck

…to handle that.  I tried the ./tests/fsaTests.py but that didn't seem to work from the master branch.

2019-07-19 10:50 UTC, dainiuskreivenas commented on association/association.py
> +    def build(self, runTime,NEAL=None,FSA=None):
Maybe these should be a separate methods, like useFsa(self, fsa), useNeal(self, neal), build() should really be without any parameters. Once we implement the prime operation, the runTime will go away as well. init method will pick either default fsa,neal or the ones passed in the use functions.

2019-07-19 10:52 UTC, ChrisHuyck commented
We can discuss it on Monday, but it seems like a way to transition from the current status to the status where we have only item (that’s the last issue I added today).
-Chris

From: dainiuskreivenas [mailto:notifications@github.com]
Sent: 19 July 2019 11:51
To: dainiuskreivenas/rbs <rbs@noreply.github.com>
Cc: Chris Huyck <C.Huyck@mdx.ac.uk>; Author <author@noreply.github.com>
Subject: Re: [dainiuskreivenas/rbs] added optional init params for neal and FSA. included a statemachine … (#6)


@dainiuskreivenas commented on this pull request.

________________________________

In association/association.py<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdainiuskreivenas%2Frbs%2Fpull%2F6%23discussion_r305305186&data=02%7C01%7Cc.huyck%40mdx.ac.uk%7Cea7be68fcfa54e0419ca08d70c36f16e%7C38e37b88a3a148cf9f056537427fed24%7C0%7C0%7C636991302430044351&sdata=NfO%2BaiSV1Iitlhrirx8com%2FxronLoU6cF9cCO1KU7nY%3D&reserved=0>:

> @@ -33,8 +44,8 @@ def setActivation(self, runTime):

             num = self.inheritance.getUnitNumber(u)

             self.fsa.halfTurnOnStateFromSpikeSource(generator, self.topology.neuralHierarchyTopology.cells, num)



-    def build(self, runTime):

-        self.init()

+    def build(self, runTime,NEAL=None,FSA=None):

Maybe these should be a separate methods, like useFsa(self, fsa), useNeal(self, neal), build() should really be without any parameters. Once we implement the prime operation, the runTime will go away as well. init method will pick either default fsa,neal or the ones passed in the use functions.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdainiuskreivenas%2Frbs%2Fpull%2F6%3Femail_source%3Dnotifications%26email_token%3DAAEGLMSZVOD3OH7MHCWA6DDQAGMABA5CNFSM4IFEWDR2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB67ILXY%23pullrequestreview-264144351&data=02%7C01%7Cc.huyck%40mdx.ac.uk%7Cea7be68fcfa54e0419ca08d70c36f16e%7C38e37b88a3a148cf9f056537427fed24%7C0%7C0%7C636991302430044351&sdata=pnbZaaGopr1IpAgSKvvXw%2FoYZTo2wo8WJHx4Kvh4Vdg%3D&reserved=0>, or mute the thread<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAEGLMQ2ZMRWSHHTKVS5SJLQAGMABANCNFSM4IFEWDRQ&data=02%7C01%7Cc.huyck%40mdx.ac.uk%7Cea7be68fcfa54e0419ca08d70c36f16e%7C38e37b88a3a148cf9f056537427fed24%7C0%7C0%7C636991302430054345&sdata=geGLrTlLfRjO3NGPP2HyL0FVVUhUTOgYIjfPtSCTwFI%3D&reserved=0>.

2019-07-19 10:57 UTC, dainiuskreivenas requested changes

2019-07-19 10:57 UTC, dainiuskreivenas commented on stateMachineClass.py
> +#Using the nealNRPCover so no nealParams
If this does not work against the tests we should revert this back or make fix it completly (but this will be quite a big job).

2019-10-03 22:04 UTC, dainiuskreivenas commented
Closing as reimplemented in #8

2019-10-03 22:04 UTC, closed without merging